spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    hikari:
      username: root
      password: root

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always
